
name: safety_mvp
description: Real-Time Safety & Trust Companion — MVP1 (Flutter)
publish_to: "none"
version: 0.1.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
